version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./../data/config:/config
      - ./../data/data1:/data1
      - ./../data/data2:/data2
    ports:
      - 8384:8384 # WebUI
      - 22000:22000/tcp #listen
      - 22000:22000/udp #listen
      - 21027:21027/udp #Discovery
    restart: always
